using DotExporterApi;

var dot = new DotBuilder("RandomGraph")
    .RankDir(DotRankDir.Lr)
    .AddNode("N1")
        .Label("Entry")
        .Shape(DotShape.Circle)
        .Color(DotColor.Green)
        .Build()
    .AddNode("N2")
        .Label("Process")
        .Shape(DotShape.Box)
        .Color(DotColor.Blue)
        .Build()
    .AddNode("N3")
        .Label("Decision")
        .Shape(DotShape.Diamond)
        .Color(DotColor.Red)
        .Build()
    .AddNode("N4")
        .Label("Exit")
        .Shape(DotShape.Circle)
        .Color(DotColor.Black)
        .Build()
    .AddEdge("N1", "N2")
        .Label("Start")
        .Build()
    .AddEdge("N2", "N3")
        .Label("Evaluate")
        .Build()
    .AddEdge("N3", "N4")
        .Label("Done")
        .Color(DotColor.LightGrey)
        .Build()
    .AddSubgraph("cluster1")
        .Label("Group A")
        .Style(DotStyle.Filled)
        .Color(DotColor.LightGrey)
        .AddNode("N2")
            .Build()
        .AddNode("N3")
            .Build()
        .Build()
    .Build();

Console.WriteLine(dot);