<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>12</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>VariableAccessingApi</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="Microsoft.CSharp" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\API\API.csproj" />
      <ProjectReference Include="..\IdentityModel\IdentityModel.csproj" />
    </ItemGroup>

</Project>
